### ISSUE TITLE
SlevomatCodingStandard\Sniffs\Whitespaces\DuplicateSpacesSniff.DuplicateSpaces breaks indentation in annotations

### ISSUE THREAD

**Issue by gnutix** [slevomat/coding-standard#1054]
Here's an example :

```diff
--- Original
+++ New
@@ -47,8 +47,8 @@
      *
      * @Assert\Type("array")
      * @Assert\All({
-     *     @Assert\NotNull,
-     *     @EntityExists(App\Domain\Tag\Tag::class)
+     * @Assert\NotNull,
+     * @EntityExists(App\Domain\Tag\Tag::class)
      * })
      */
     public $tags = [];
```

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard#slevomatcodingstandardwhitespacesduplicatespaces-

**Comment by gnutix** [comment]
```yaml
# easy-coding-standard.yaml
services:
    SlevomatCodingStandard\Sniffs\Whitespaces\DuplicateSpacesSniff:
        ignoreSpacesInAnnotation: true
```

fixed it. Thanks! However, wouldn't it make sense to be true by default for this one ? (don't know what's the general policy for defaults on this sniff library)
