### ISSUE TITLE
Conflict between SlevomatCodingStandard\Sniffs\Classes\TraitUseSpacingSniff and PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\FunctionSpacingSniff

### ISSUE THREAD

**Issue by JanMikes** [slevomat/coding-standard#474]
Hello!

We would love to achieve 1 space between trait uses, 1 between properties and trait uses, 2 before first function. Though this might seem as easy task, we have run into circular conflict, unable to make sniffer pass. Tricky part seems to be in the "2 lines before first function".¨

With following settings:
```yml
PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\MemberVarSpacingSniff:
        spacing: 1
        spacingBeforeFirst: 0

PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\FunctionSpacingSniff:
        spacing: 2
        spacingBeforeFirst: 0
        spacingAfterLast: 0

SlevomatCodingStandard\Sniffs\Classes\TraitUseSpacingSniff:
        linesCountAfterLastUse: 1
        linesCountAfterLastUseWhenLastInClass: 0
        linesCountBeforeFirstUse: 0
        linesCountBetweenUses: 1
```

What is happening to us is when we run sniffer:
```php
        use StaticClass;
 
-
        public static function createRouter(): IRouter
        {
                $router = new RouteList();

```
after we fix it, we have this:
```php
        use StaticClass;
 
+
        public static function createRouter(): IRouter
        {
                $router = new RouteList();
```

Any tips how to get rid of this circular hell? :-)
